version: 2

sources:
  - name: sap 
    schema: sap_adw  
    tables:
      
      - name: product
        description: Tabela de produtos comercializados pela Adventure Works.
        columns:
          - name: productid
            tests:
              - unique
              - not_null
      - name: productsubcategory    
        description: Subcategoria dos produtos.
      - name: productcategory
        description: Categoria dos produtos.


      - name: person
        description: Lista de clientes da Adventure Works. 
        columns:
          - name: businessentityid
            tests:
              - unique 
              - not_null
      - name: personcreditcard
        description: Lista de cartão de credito dos clientes.
      - name: creditcard
        description: Lista de detalhes de cartão de credito dos clientes. 
      - name: address
        description: Lista de endereço dos clientes da Adventure Works.
      - name: stateprovince
        description: Lista de cidades dos clientes da Adventure Works.
      - name: countryregion
        description: Lista de paises dos clientes da Adventure Works.

      - name: salesorderheader
        description: Lista de vendas da Adventure Works. 
        columns:
          - name: businessentityid
            tests:
              - unique 
              - not_null
      - name: salesorderdetail
        description: Lista de detalhes de vendas da Adventure Works.
      - name: salesorderheadersalesreason
        description: Lista de razões de vendas da Adventure Works.
      - name: salesreason
        description: Lista de tipo de razões de vendas da Adventure Works.

    
