version: 2

sources:
  - name: sap 
    schema: sap_adw  
    tables:
      - name: employee
        description: Tabela de funcionarios da Aventure Works.
        columns:
          - name: businessentityid
            tests:
              - unique 
              - not_null 

      - name: product
        description: Tabela de produtos comercializados pela Adventure Works.
        columns:
          - name: productid
            tests:
              - unique
              - not_null
      - name: productlistpricehistory
        description: Lista do historico de preços dos produtos.
      - name: productsubcategory    
        description: Subcategoria dos produtos.
      - name: productcategory
        description: Categoria dos produtos.
      - name: workorder
        description: Tabela de ordem de serviço.
      - name: productcosthistory
        description: Tabela preço de custo.
