version: 2

sources:
  - name: sap 
    schema: sap_adw  
    tables:
      - name: product
        columns:
          - name: id_product
            tests:
              - unique
              - not_null
              