version: 2

sources:
  - name: sap 
    schema: sap_adw  
    tables:
      - name: employee
        description: Tabela de funcionarios da Aventure Works.
        columns:
          - name: businessentityid
            tests:
              - unique 
              - not_null 

              

      - name: product
        description: Tabela de produtos comercializados pela Adventure Works.
        columns:
          - name: productid
            tests:
              - unique
              - not_null
      - name: productlistpricehistory
        description: Lista do historico de preços dos produtos.
      - name: productsubcategory    
        description: Subcategoria dos produtos.
      - name: productcategory
        description: Categoria dos produtos.
      - name: workorder
        description: Tabela de ordem de serviço.
      - name: productcosthistory
        description: Tabela preço de custo.


      - name: person
        description: Lista de clientes da Adventure Works. 
        columns:
          - name: businessentityid
            tests:
              - unique 
              - not_null
      - name: personcreditcard
        description: Lista de cartão de credito dos clientes.
      - name: creditcard
        description: Lista de detalhes de cartão de credito dos clientes. 
      - name: businessentityaddress
        description: Lista de id do endereço de cada cliente. 
      - name: address
        description: Lista de endereço dos clientes da Adventure Works.
      - name: stateprovince
        description: Lista de cidades dos clientes da Adventure Works.
      - name: businessentity
        description: Lista de businees id dos clientes da Adventure Works.


    
